var screentopdata=[
    {
        "title":"商城类型",
        "sign":"type",
        "array":["旗舰店","专营店","专卖店"]
    },
    {
        "title":"商标类型",
        "sign":"trademarks",
        "array":["无","R","TM"]
    },
    {
        "title":"所在地区",
        "sign":"area",
        "array":["华南地区","华北地区","华东地区","华中地区","西南地区","西北地区","海外地区"]
    },
]

//price单位为万

var screenbottomdata=[
    {
        "name":"华北地区旗舰店R标",
        "type":"旗舰店",
        "trademarks":"R",
        "area":"华北地区",
        "price":"3.00"
    },
    {
        "name":"华中地区旗舰店R标",
        "type":"旗舰店",
        "trademarks":"R",
        "area":"华中地区",
        "price":"50.00"
    },
    {
        "name":"华东地区旗舰店TM标",
        "type":"旗舰店",
        "trademarks":"TM",
        "area":"华东地区",
        "price":"35.00"
    },
    {
        "name":"西北地区专营店TM标",
        "type":"专营店",
        "trademarks":"TM",
        "area":"华东地区",
        "price":"45.00"
    },
    {
        "name":"西南地区专营店无标",
        "type":"专营店",
        "trademarks":"无",
        "area":"西南地区",
        "price":"12.00"
    },
    {
        "name":"海外地区专卖店R标",
        "type":"专卖店",
        "trademarks":"R",
        "area":"海外地区",
        "price":"9.00"
    },
    {
        "name":"海外地区专卖店TM标",
        "type":"专卖店",
        "trademarks":"TM",
        "area":"海外地区",
        "price":"15.00"
    }
]